# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnPressMe = QtWidgets.QPushButton(self.centralwidget)
        self.btnPressMe.setGeometry(QtCore.QRect(200, 320, 201, 111))
        self.btnPressMe.setObjectName("btnPressMe")
        self.labelMain = QtWidgets.QLabel(self.centralwidget)
        self.labelMain.setGeometry(QtCore.QRect(100, 10, 621, 291))
        self.labelMain.setObjectName("labelMain")
        self.btnShowImg = QtWidgets.QPushButton(self.centralwidget)
        self.btnShowImg.setGeometry(QtCore.QRect(410, 320, 201, 111))
        self.btnShowImg.setObjectName("btnShowImg")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnPressMe.setText(_translate("MainWindow", "Press me!"))
        self.labelMain.setText(_translate("MainWindow", "Hello World!"))
        self.btnShowImg.setText(_translate("MainWindow", "Show image"))
